name: hqm-virus
main: me.hqm.virus.Infect
version: ${project.version}
description: Totes not a virus.
authors: [HQM]
commands:
  rainbowarmor:
    usage: /rainbowarmor
permissions:
  hqm.rainbowarmor:
    default: op